"""Add Risk Story fields to Patient

Revision ID: 404b89dd0189
Revises: c17620c6b23b
Create Date: 2026-10-05 21:48:52.317225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '404b89dd0189'
down_revision: Union[str, Sequence[str], None] = 'c17620c6b23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('risk_story', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patients', sa.Column('risk_story_fingerprint', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('risk_story_model', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('risk_story_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'risk_story_generated_at')
    op.drop_column('patients', 'risk_story_model')
    op.drop_column('patients', 'risk_story_fingerprint')
    op.drop_column('patients', 'risk_story')
    # ### end Alembic commands ###
