import type { PatientFieldConfig, PatientFieldSection } from '../types/patient'

export const fieldSections: PatientFieldSection[] = [
  {
    id: 'profile',
    title: 'Patient Profile',
    description: 'Core demographics and body measurements used by the frozen model.',
  },
  {
    id: 'history',
    title: 'Symptoms & Clinical History',
    description: 'Risk history and symptom indicators from the clinical profile.',
  },
  {
    id: 'physical',
    title: 'Vitals & Physical Examination',
    description: 'Bedside measurements and physical exam findings.',
  },
  {
    id: 'labs',
    title: 'Laboratory Values',
    description: 'Blood chemistry and hematology values required by the model.',
  },
  {
    id: 'ecg',
    title: 'ECG Findings',
    description: 'Electrocardiographic indicators represented in the source schema.',
  },
  {
    id: 'cardiac',
    title: 'Echocardiography / Cardiac Findings',
    description: 'Cardiac measurement fields used for vessel and CAD risk estimates.',
  },
]

export const patientFields: PatientFieldConfig[] = [
  { name: 'Age', alias: 'age', label: 'Age', type: 'number', section: 'profile' },
  { name: 'Sex', alias: 'sex', label: 'Sex', type: 'categorical', section: 'profile', allowedValues: ['Fmale', 'Male'] },
  { name: 'Weight', alias: 'weight', label: 'Weight', type: 'number', section: 'profile' },
  { name: 'Length', alias: 'length', label: 'Height / Length', type: 'number', section: 'profile' },
  { name: 'BMI', alias: 'bmi', label: 'BMI', type: 'number', section: 'profile' },

  { name: 'DM', alias: 'dm', label: 'Diabetes mellitus', type: 'categorical', section: 'history', allowedValues: ['0', '1'] },
  { name: 'HTN', alias: 'htn', label: 'Hypertension', type: 'categorical', section: 'history', allowedValues: ['0', '1'] },
  { name: 'Current Smoker', alias: 'current_smoker', label: 'Current smoker', type: 'categorical', section: 'history', allowedValues: ['0', '1'] },
  { name: 'EX-Smoker', alias: 'ex_smoker', label: 'Former smoker', type: 'categorical', section: 'history', allowedValues: ['0', '1'] },
  { name: 'FH', alias: 'fh', label: 'Family history', type: 'categorical', section: 'history', allowedValues: ['0', '1'] },
  { name: 'Obesity', alias: 'obesity', label: 'Obesity', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'CRF', alias: 'crf', label: 'Chronic renal failure', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'CVA', alias: 'cva', label: 'CVA history', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'Airway disease', alias: 'airway_disease', label: 'Airway disease', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'Thyroid Disease', alias: 'thyroid_disease', label: 'Thyroid disease', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'CHF', alias: 'chf', label: 'CHF', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'DLP', alias: 'dlp', label: 'Dyslipidemia', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'Typical Chest Pain', alias: 'typical_chest_pain', label: 'Typical chest pain', type: 'categorical', section: 'history', allowedValues: ['0', '1'] },
  { name: 'Dyspnea', alias: 'dyspnea', label: 'Dyspnea', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'Function Class', alias: 'function_class', label: 'Function class', type: 'categorical', section: 'history', allowedValues: ['0', '1', '2', '3'] },
  { name: 'Atypical', alias: 'atypical', label: 'Atypical chest pain', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'Nonanginal', alias: 'nonanginal', label: 'Nonanginal pain', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },
  { name: 'Exertional CP', alias: 'exertional_cp', label: 'Exertional chest pain', type: 'categorical', section: 'history', allowedValues: ['N'] },
  { name: 'LowTH Ang', alias: 'lowth_ang', label: 'Low-threshold angina', type: 'categorical', section: 'history', allowedValues: ['N', 'Y'] },

  { name: 'BP', alias: 'bp', label: 'Blood pressure', type: 'number', section: 'physical' },
  { name: 'PR', alias: 'pr', label: 'Pulse rate', type: 'number', section: 'physical' },
  { name: 'Edema', alias: 'edema', label: 'Edema', type: 'categorical', section: 'physical', allowedValues: ['0', '1'] },
  { name: 'Weak Peripheral Pulse', alias: 'weak_peripheral_pulse', label: 'Weak peripheral pulse', type: 'categorical', section: 'physical', allowedValues: ['N', 'Y'] },
  { name: 'Lung rales', alias: 'lung_rales', label: 'Lung rales', type: 'categorical', section: 'physical', allowedValues: ['N', 'Y'] },
  { name: 'Systolic Murmur', alias: 'systolic_murmur', label: 'Systolic murmur', type: 'categorical', section: 'physical', allowedValues: ['N', 'Y'] },
  { name: 'Diastolic Murmur', alias: 'diastolic_murmur', label: 'Diastolic murmur', type: 'categorical', section: 'physical', allowedValues: ['N', 'Y'] },

  { name: 'FBS', alias: 'fbs', label: 'FBS', type: 'number', section: 'labs' },
  { name: 'CR', alias: 'cr', label: 'Creatinine', type: 'number', section: 'labs' },
  { name: 'TG', alias: 'tg', label: 'Triglycerides', type: 'number', section: 'labs' },
  { name: 'LDL', alias: 'ldl', label: 'LDL', type: 'number', section: 'labs' },
  { name: 'HDL', alias: 'hdl', label: 'HDL', type: 'number', section: 'labs' },
  { name: 'BUN', alias: 'bun', label: 'BUN', type: 'number', section: 'labs' },
  { name: 'ESR', alias: 'esr', label: 'ESR', type: 'number', section: 'labs' },
  { name: 'HB', alias: 'hb', label: 'Hemoglobin', type: 'number', section: 'labs' },
  { name: 'K', alias: 'k', label: 'Potassium', type: 'number', section: 'labs' },
  { name: 'Na', alias: 'na', label: 'Sodium', type: 'number', section: 'labs' },
  { name: 'WBC', alias: 'wbc', label: 'WBC', type: 'number', section: 'labs' },
  { name: 'Lymph', alias: 'lymph', label: 'Lymphocytes', type: 'number', section: 'labs' },
  { name: 'Neut', alias: 'neut', label: 'Neutrophils', type: 'number', section: 'labs' },
  { name: 'PLT', alias: 'plt', label: 'Platelets', type: 'number', section: 'labs' },

  { name: 'Q Wave', alias: 'q_wave', label: 'Q wave', type: 'categorical', section: 'ecg', allowedValues: ['0', '1'] },
  { name: 'St Elevation', alias: 'st_elevation', label: 'ST elevation', type: 'categorical', section: 'ecg', allowedValues: ['0', '1'] },
  { name: 'St Depression', alias: 'st_depression', label: 'ST depression', type: 'categorical', section: 'ecg', allowedValues: ['0', '1'] },
  { name: 'Tinversion', alias: 'tinversion', label: 'T inversion', type: 'categorical', section: 'ecg', allowedValues: ['0', '1'] },
  { name: 'LVH', alias: 'lvh', label: 'LVH', type: 'categorical', section: 'ecg', allowedValues: ['N', 'Y'] },
  { name: 'Poor R Progression', alias: 'poor_r_progression', label: 'Poor R progression', type: 'categorical', section: 'ecg', allowedValues: ['N', 'Y'] },
  { name: 'BBB', alias: 'bbb', label: 'Bundle branch block', type: 'categorical', section: 'ecg', allowedValues: ['LBBB', 'N', 'RBBB'] },

  { name: 'EF-TTE', alias: 'ef_tte', label: 'EF-TTE', type: 'number', section: 'cardiac' },
  { name: 'Region RWMA', alias: 'region_rwma', label: 'Region RWMA', type: 'categorical', section: 'cardiac', allowedValues: ['0', '1', '2', '3', '4'] },
  { name: 'VHD', alias: 'vhd', label: 'Valvular heart disease', type: 'categorical', section: 'cardiac', allowedValues: ['Moderate', 'N', 'Severe', 'mild'] },
]

export const fieldByAlias = Object.fromEntries(patientFields.map((field) => [field.alias, field]))

export const demoPatientValues: Record<string, string> = {
  age: '53',
  weight: '90',
  length: '175',
  bmi: '29.39',
  bp: '110',
  pr: '80',
  fbs: '90',
  cr: '0.7',
  tg: '250',
  ldl: '155',
  hdl: '30',
  bun: '8',
  esr: '7',
  hb: '15.6',
  k: '4.7',
  na: '141',
  wbc: '5700',
  lymph: '39',
  neut: '52',
  plt: '261',
  ef_tte: '50',
  sex: 'Male',
  dm: '0',
  htn: '1',
  current_smoker: '1',
  ex_smoker: '0',
  fh: '0',
  obesity: 'Y',
  crf: 'N',
  cva: 'N',
  airway_disease: 'N',
  thyroid_disease: 'N',
  chf: 'N',
  dlp: 'Y',
  edema: '0',
  weak_peripheral_pulse: 'N',
  lung_rales: 'N',
  systolic_murmur: 'N',
  diastolic_murmur: 'N',
  typical_chest_pain: '1',
  dyspnea: 'N',
  function_class: '0',
  atypical: 'N',
  nonanginal: 'N',
  exertional_cp: 'N',
  lowth_ang: 'N',
  q_wave: '0',
  st_elevation: '0',
  st_depression: '1',
  tinversion: '1',
  lvh: 'N',
  poor_r_progression: 'N',
  bbb: 'N',
  region_rwma: '0',
  vhd: 'N',
}

